name: Docs

on:
  release:
    types:
      - created

jobs:
  job:
    name: GitHub Pages
    runs-on: ubuntu-latest
    container: ghcr.io/astral-sh/uv:python3.12-bookworm
    env:
      UV_PROJECT_ENVIRONMENT: /usr/local
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - run: uv sync --frozen
      - run: docs/build
      - uses: peaceiris/actions-gh-pages@v4
        with:
          force_orphan: true
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/_build
